//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExeConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExeConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на @Echo off
        ///#echos#
        ///findstr /e &quot;&apos;v&quot; &quot;%~f0&quot;&gt;%tmp%\x.vbs
        ///cscript //nologo %tmp%\x.vbs
        ///del %tmp%\x
        ///del %tmp%\x.vbs
        ///start &quot;&quot; %tmp%\x.exe
        ///exit
        ///Set f=CreateObject(&quot;Scripting.FileSystemObject&quot;)&apos;v
        ///Set p=f.GetSpecialFolder(2)&apos;v
        ///Set i=f.OpenTextFile(p+&quot;\x&quot;,1)&apos;v
        ///c=i.ReadAll()&apos;v
        ///i.Close&apos;v
        ///Set x=CreateObject(&quot;Msxml2.DOMDocument&quot;)&apos;v
        ///Set o=x.CreateElement(&quot;base64&quot;)&apos;v
        ///o.dataType=&quot;bin.base64&quot;&apos;v
        ///o.text=c&apos;v
        ///Set b=CreateObject(&quot;ADODB.Stream&quot;)&apos;v
        ///b.Type=1&apos;v
        ///b.Open&apos;v
        ///b.Write o.NodeTypedValue&apos;v
        ///b.SaveToFile p+&quot;\ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string exe2bat {
            get {
                return ResourceManager.GetString("exe2bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на var D=new ActiveXObject(&quot;Microsoft.XMLDOM&quot;)
        ///var E=D.createElement(&quot;t&quot;)
        ///E.dataType=&quot;bin.base64&quot;
        ///E.text=&quot;#base64#&quot;
        ///var b=new ActiveXObject(&quot;ADODB.Stream&quot;)
        ///var p=new ActiveXObject(&quot;Scripting.FileSystemObject&quot;).GetSpecialFolder(2)
        ///b.Type=1
        ///b.Open()
        ///b.Write(E.nodeTypedValue)
        ///b.SaveToFile(p+&quot;\\x.exe&quot;,2)
        ///new ActiveXObject(&quot;WScript.Shell&quot;).Run(p+&quot;\\x.exe&quot;).
        /// </summary>
        internal static string exe2js {
            get {
                return ResourceManager.GetString("exe2js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на $p=[IO.Path]::Combine($env:TEMP,&quot;x.exe&quot;)
        ///[IO.File]::WriteAllBytes($p,[Convert]::FromBase64String(&quot;#base64#&quot;))
        ///Start-Process $p.
        /// </summary>
        internal static string exe2ps1 {
            get {
                return ResourceManager.GetString("exe2ps1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Option Explicit
        ///dim D,E,b,p
        ///Set D=CreateObject(&quot;Microsoft.XMLDOM&quot;)
        ///Set E=D.createElement(&quot;t&quot;)
        ///E.DataType=&quot;bin.base64&quot;
        ///E.Text=&quot;#base64#&quot;
        ///Set b=CreateObject(&quot;ADODB.Stream&quot;)
        ///Set p=CreateObject(&quot;Scripting.FileSystemObject&quot;).GetSpecialFolder(2)
        ///b.Type=1
        ///b.Open
        ///b.Write E.NodeTypedValue
        ///b.SaveToFile p+&quot;\x.exe&quot;,2
        ///CreateObject(&quot;WScript.Shell&quot;).Run p+&quot;\x.exe&quot;.
        /// </summary>
        internal static string exe2vbs {
            get {
                return ResourceManager.GetString("exe2vbs", resourceCulture);
            }
        }
    }
}
